First 7 chapters are ready for code review
balazsvitus/online-shop-frontend pull request #1
Opened 2024-07-29 08:52 UTC by balazsvitus

2024-07-29 10:17 UTC, mmalin7 requested changes

2024-07-29 10:17 UTC, mmalin7 commented on src/App.tsx
> +        <Route path="*" element={<Navigate to="/products" replace={true} />} />
I don't think it was described in the training but for routes that we don't have we can create a 404 page that we can display.
When the user navigate through you app it will not end up on a non-existing pages but maybe the user wants to write by hand the route and if this is wrong we should redirect to a 404.
For example I want to go on the page /cart and for some reason I write it in the URL but wrong: "/crat". I should end up on a 404 page and not on the /products page as in this case.

2024-07-29 10:17 UTC, mmalin7 commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
Nice little touch

2024-07-29 10:17 UTC, mmalin7 commented on src/features/products/hooks/useProductDetails.ts
> +    const response = axiosInstance.get<ProductDetailType>(
I see you used the try, catch mechanism with await for these kind of calls. Try to stay consistent using one of these ways of dealing with Promises in all places.

2024-07-29 10:17 UTC, mmalin7 commented on src/lib/axiosInstance.ts
> +  baseURL: 'http://localhost:3000',
Use here the API_BASE_URL from the new file.

2024-07-29 10:17 UTC, mmalin7 commented on src/features/products/hooks/useProductDetails.ts
> +        await axiosInstance.delete(`/products/${productId}`);
I think a good idea would be to extract all backend URLs called by the frontend in a separate file.
It helps in maintaining a clean codebase, makes it easier to update URLs, and improves readability.
````
const API_BASE_URL = 'http://localhost:3000';
const API_URLS = {
  PRODUCTS: '/products',
  ...
};

export default API_URLS;
````
And then import it an use here.

2024-07-29 10:17 UTC, mmalin7 commented on src/features/products/components/ProductsTableItem.tsx
> +  const handleNavigate = (productId: string) => {
Here I think we can improve just a little the app.
Let's say we are on /products page. We can go on the page of a specific product in 2 ways: 
- by clicking on the product in the table
- by changing the URL to /products/c49e49f6-ee3f-4897-a75c-53e9f9152248 (let's assume I know this from my head)

Right now you navigate to that page and then fetch the product from the backend.
But what we could do is:
- if the user clicks on the product in the table we send it as props because we have all details about the product (I think): ````navigate(`/products/${product.id}`, { state: { product } });````
- if the user changes the URL or refreshes the page we do a call to backend to get the details.

This change probably requires some changes to the useProductDetails hook. Implement it only if you have time and want to see how this works. Basically with this we would spare some calls to the backend.

2024-07-29 10:17 UTC, mmalin7 commented on src/features/shoppingCart/pages/ShoppingCart.tsx
> +          style={{
You should stay consistent and have CSS only in the special css files.

2024-07-29 10:27 UTC, mmalin7 commented on src/features/products/styles/products.module.css
> +.centerTableContainer {
Ussually there is a naming convention here:

![image](https://github.com/user-attachments/assets/55b73ef4-b634-4375-89f7-7402731a1697)

**You don't have to change this now but keep this in mind for future.**

2024-07-29 10:27 UTC, mmalin7 commented on src/features/products/styles/productDetails.module.css
> +.centerDetailsContainer {
I see some of these classes also exist in the Products CSS file but just with some other naming. Of course re-use applies for CSS too so if there are some general CSS classes only for centering or so, these can be extracted in App.css for example and used in all places from there.

**You don't have to change anything just keep in mind for future.**

2024-07-29 10:27 UTC, mmalin7 commented on src/features/products/styles/products.module.css
> +.tableContainer {
Also related to naming the files have a different namiNg conventions as well.
Ussually is either ProductsDetails.module.css or prodcuts-details.module.css depending on how the components are called.

**You don't have to change this now but keep this in mind for future.**

2024-07-29 12:13 UTC, balazsvitus commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
thankieees

2024-07-29 13:19 UTC, balazsvitus commented on src/App.tsx
> +        <Route path="*" element={<Navigate to="/products" replace={true} />} />
done

2024-07-29 13:19 UTC, balazsvitus commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
thankies

2024-07-29 13:21 UTC, balazsvitus commented on src/features/products/hooks/useProductDetails.ts
> +    const response = axiosInstance.get<ProductDetailType>(
done

2024-07-29 13:24 UTC, balazsvitus commented on src/features/products/hooks/useProductDetails.ts
> +        await axiosInstance.delete(`/products/${productId}`);
done

2024-07-29 13:25 UTC, balazsvitus commented on src/features/shoppingCart/pages/ShoppingCart.tsx
> +          style={{
done

2024-07-29 13:32 UTC, balazsvitus commented on src/features/products/styles/products.module.css
> +.tableContainer {
done

2024-07-29 14:12 UTC, balazsvitus commented on src/features/products/components/ProductsTableItem.tsx
> +  const handleNavigate = (productId: string) => {
almost done, having infinite loop, fixing now

2024-07-29 14:13 UTC, balazsvitus commented on src/lib/axiosInstance.ts
> +  baseURL: 'http://localhost:3000',
done

2024-07-29 14:23 UTC, balazsvitus commented on src/features/products/components/ProductsTableItem.tsx
> +  const handleNavigate = (productId: string) => {
done [afca96d](https://github.com/balazsvitus/online-shop-frontend/pull/1/commits/afca96d441c9df4ebec53689e07c3fd20667adc6)

2024-07-29 14:28 UTC, balazsvitus commented on src/features/products/styles/productDetails.module.css
> +.centerDetailsContainer {
Moved reused CSS classes into App.css

2024-07-30 06:56 UTC, mmalin7 approved these changes

2024-07-30 06:56 UTC, mmalin7 commented on src/features/shoppingCart/hooks/useShoppingCart.ts
> +        const response = await fetch('http://localhost:3000/orders', {
You can extract this also in the files with URL and use it like API_BASE_URL + API_URL.ORDERS

2024-07-30 06:56 UTC, mmalin7 commented on src/contexts/ShoppingCartContext.tsx
> +      value={{
Maybe one interesting way of improving here would be using "useMemo" hook.
The "useMemo" hook should help to memoize the context value, preventing unnecessary re-renders.

````
const value = useMemo(() => ({
    shoppingCart,
    addToShoppingCart,
    removeFromShoppingCart,
    emptyShoppingCart,
  }), [shoppingCart]);

  return (
    <ShoppingCartContext.Provider value={value}>
      {children}
    </ShoppingCartContext.Provider>
  );
````

2024-07-30 07:01 UTC, balazsvitus commented on src/features/shoppingCart/hooks/useShoppingCart.ts
> +        const response = await fetch('http://localhost:3000/orders', {
done

2024-07-30 07:45 UTC, balazsvitus commented on src/contexts/ShoppingCartContext.tsx
> +      value={{
Done, and re-read the useMemo documentation too, searched for use-cases and understood when to use. I knew about the useMemo hook before too, I just never used it before, so I didn't have a good example in my head when I could use it.

2024-07-30 07:46 UTC, merged